title: SCloud Documentation
description: Find technical documentation for SCloud services, SDKs and toolkits, use cases, scenarios, and tasks. Browse user guides, developer guides, tutorials, and API references.
theme: just-the-docs

url: https://scloud-pte-ltd.github.io

aux_links:
  SCloud Homepage: https://www.scloud.sg/

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/scloud-logo.png"
# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/images/favicon-32x32.png"

# Footer content
footer_content: "GLOBAL FOOTPRINT WITH ASIA FOCUS | FLEXIBLE | 24/7/365 SUPPORT | VALUE-ADDED SERVICES"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/SCLOUD-PTE-LTD/docs" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source:  # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

color_scheme: custom